version: '3.4'

# Common variables
x-common-variables: &common-variables
  HBFDHOSTPORT: ${HBFDHOSTPORT}

x-xxx-common-services-config: &common-services-config
  restart: always

x-kafka-env: &kafka-env
  KAFKA_BROKER_ID: 1
  KAFKA_ADVERTISED_PORT: 9092
  BROKER_ID_COMMAND: "hostname | cut -d'-' -f2"
  KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
  KAFKA_CREATE_TOPICS: "logging:20:1,pushnotifications:10:1,invoicing:10:1,mailing:10:1,userupdates:10:1,orderupdates:10:1"
  KAFKA_LISTENERS: "PLAINTEXT://:9092"

services:
  pingackfd:
    <<: *common-services-config
    build:
      context: .
      dockerfile: PingAckFaultDetector/Dockerfile
    ports:
      - "8080:8080"
    environment:
      <<: *common-variables
      HOST_LIST: ${HOST_LIST}
      PING_POOLING_TIME: ${PING_POOLING_TIME}
      HEARTBEAT_RESEND_TIME: ${HEARTBEAT_RESEND_TIME}
#    volumes:
#      - mystorage:

  testclient:
    <<: *common-services-config
    build:
      context: .
      dockerfile: TestClient/Dockerfile
    ports:
      - "8081:8080"
    environment:
      <<: *common-variables
#    volumes:
#      - mystorage:

  testheartbeat:
    <<: *common-services-config
    build:
      context: .
      dockerfile: TestHeartBeat/Dockerfile
    ports:
      - "8082:8080"
    environment:
      <<: *common-variables
#    volumes:
#      - mystorage:

  zoo:
    <<: *common-services-config
    image: library/zookeeper:3.4.13
    environment:
      <<: *common-variables
      ZOO_MY_ID: 1

  kafka:
    <<: *common-services-config
    environment:
      <<: *common-variables
      <<: *kafka-env
    image: wurstmeister/kafka:2.11-2.0.0

volumes:
  mystorage: