apiVersion: v1
kind: ConfigMap
metadata:
  name: pingackfd-env
data:
  KAFKA_ADDRESS: kafkabroker.default.svc.cluster.local:9092
  KAFKA_MAIN_TOPIC: logging
  HBFDHOSTPORT: testheartbeat.default.svc.cluster.local:8080
  HEARTBEAT_RESEND_TIME: "30000"
  PING_POOLING_TIME: "30000"
  HOST_LIST: testclient.default.svc.cluster.local:8080
